"""Command handlers for IRIS.

HANDLERS maps every command name in commands/registry.py to its handler.
Register them with the executor:

    from commands.handlers import HANDLERS
    executor.register_handlers(HANDLERS)

Each handler's parameter names match the registry exactly, because the executor
calls handler(**parameters).
"""

from commands.handlers.ai import (
    analyze_file,
    analyze_text,
    ask_ai,
    ai_fallback,
    explain,
    generate_text,
    rewrite,
    summarize,
    translate,
)
from commands.handlers.applications import (
    check_app_status,
    close_app,
    focus_app,
    install_app,
    maximize_app,
    minimize_app,
    open_app,
    restart_app,
    switch_app,
    uninstall_app,
)
from commands.handlers.audio import (
    mute,
    next_track,
    pause_media,
    play_music,
    play_video,
    previous_track,
    resume_media,
    set_volume,
    stop_media,
    stop_video,
    unmute,
    volume_down,
    volume_up,
)
from commands.handlers.automation import (
    create_automation,
    execute_task,
    list_automations,
    run_automation,
    run_sequence,
    stop_automation,
)
from commands.handlers.browser import (
    back,
    bookmark_page,
    change_tab,
    clear_browser_data,
    close_tab,
    close_website,
    download_file,
    forward,
    go_to_url,
    google_search,
    new_tab,
    open_bookmark,
    open_website,
    refresh_page,
    reopen_tab,
    search_website,
    stop_download,
    switch_tab,
)
from commands.handlers.clipboard import (
    clear_clipboard,
    clipboard_history,
    copy,
    paste,
    read_clipboard,
    write_clipboard,
)
from commands.handlers.files import (
    cancel_deletion,
    close_file,
    close_folder,
    compress_file,
    confirm_deletion,
    copy_file,
    copy_folder,
    create_file,
    create_folder,
    delete_file,
    delete_folder,
    edit_file,
    empty_recycle_bin,
    extract_file,
    get_file_info,
    get_folder_info,
    list_folder,
    move_file,
    move_folder,
    open_file,
    open_folder,
    read_file,
    rename_file,
    rename_folder,
    search_file,
    search_folder,
)
from commands.handlers.hardware import (
    audio_device_info,
    battery_health,
    cpu_status,
    disk_status,
    display_info,
    gpu_status,
    microphone_status,
    ram_status,
    temperature_status,
)
from commands.handlers.iris import (
    change_wake_word,
    disable_wake_word,
    enable_wake_word,
    iris_status,
    restart_iris,
    sleep_mode,
    stop_iris,
    text_mode,
    voice_mode,
    wake_iris,
    wake_word,
)
from commands.handlers.network import (
    bluetooth_off,
    bluetooth_on,
    bluetooth_status,
    connect_wifi,
    disconnect_wifi,
    network_info,
    ping_host,
    wifi_off,
    wifi_on,
    wifi_status,
)
from commands.handlers.processes import (
    check_process_status,
    find_process,
    kill_process,
    list_processes,
    process_info,
    start_process,
    stop_process,
)
from commands.handlers.productivity import (
    cancel_timer,
    create_document,
    create_note,
    create_reminder,
    delete_note,
    edit_note,
    open_calendar,
    open_document,
    read_note,
    set_timer,
)
from commands.handlers.search import (
    calculate,
    get_date,
    get_time,
    news,
    search_files,
    search_pc,
    web_search,
    weather,
)
from commands.handlers.security import (
    change_password,
    check_running_processes,
    check_security_status,
    disable_firewall,
    enable_firewall,
)
from commands.handlers.screen import (
    drag,
    mouse_click,
    mouse_move,
    press_key,
    press_keys,
    scroll,
    screen_record,
    screenshot,
    screenshot_full,
    screenshot_region,
    screenshot_window,
    stop_screen_record,
    type_text,
)
from commands.handlers.software import (
    check_updates,
    launch_software,
    install_software,
    list_installed_software,
    uninstall_software,
    update_software,
)
from commands.handlers.system import (
    battery_status,
    cancel_shutdown,
    cpu_usage,
    disk_usage,
    exit_iris,
    gpu_usage,
    hibernate,
    lock_pc,
    log_out,
    network_status,
    os_info,
    ram_usage,
    restart,
    shutdown,
    sleep,
    system_info,
)
from commands.handlers.windows import (
    close_window,
    focus_window,
    lock_screen,
    maximize_window,
    minimize_window,
    move_window,
    resize_window,
    restore_window,
    show_desktop,
    snap_window,
    switch_window,
)

__all__ = ["HANDLERS"]

HANDLERS = {
    # FILES
    "OPEN_FILE": open_file,
    "CLOSE_FILE": close_file,
    "CREATE_FILE": create_file,
    "DELETE_FILE": delete_file,
    "EDIT_FILE": edit_file,
    "READ_FILE": read_file,
    "OPEN_FOLDER": open_folder,
    "CLOSE_FOLDER": close_folder,
    "CREATE_FOLDER": create_folder,
    "DELETE_FOLDER": delete_folder,
    "CONFIRM_DELETION": confirm_deletion,
    "CANCEL_DELETION": cancel_deletion,
    "RENAME_FILE": rename_file,
    "RENAME_FOLDER": rename_folder,
    "COPY_FILE": copy_file,
    "COPY_FOLDER": copy_folder,
    "MOVE_FILE": move_file,
    "MOVE_FOLDER": move_folder,
    "SEARCH_FILE": search_file,
    "SEARCH_FOLDER": search_folder,
    "LIST_FOLDER": list_folder,
    "GET_FILE_INFO": get_file_info,
    "GET_FOLDER_INFO": get_folder_info,
    "COMPRESS_FILE": compress_file,
    "EXTRACT_FILE": extract_file,
    "EMPTY_RECYCLE_BIN": empty_recycle_bin,
    # APPLICATIONS
    "OPEN_APP": open_app,
    "CLOSE_APP": close_app,
    "RESTART_APP": restart_app,
    "MINIMIZE_APP": minimize_app,
    "MAXIMIZE_APP": maximize_app,
    "FOCUS_APP": focus_app,
    "SWITCH_APP": switch_app,
    "INSTALL_APP": install_app,
    "UNINSTALL_APP": uninstall_app,
    "CHECK_APP_STATUS": check_app_status,
    # BROWSER
    "OPEN_WEBSITE": open_website,
    "CLOSE_WEBSITE": close_website,
    "CHANGE_TAB": change_tab,
    "GOOGLE_SEARCH": google_search,
    "NEW_TAB": new_tab,
    "CLOSE_TAB": close_tab,
    "REOPEN_TAB": reopen_tab,
    "SWITCH_TAB": switch_tab,
    "BACK": back,
    "FORWARD": forward,
    "REFRESH_PAGE": refresh_page,
    "GO_TO_URL": go_to_url,
    "DOWNLOAD_FILE": download_file,
    "STOP_DOWNLOAD": stop_download,
    "SEARCH_WEBSITE": search_website,
    "BOOKMARK_PAGE": bookmark_page,
    "OPEN_BOOKMARK": open_bookmark,
    "CLEAR_BROWSER_DATA": clear_browser_data,
    # WINDOWS
    "MINIMIZE_WINDOW": minimize_window,
    "MAXIMIZE_WINDOW": maximize_window,
    "RESTORE_WINDOW": restore_window,
    "MOVE_WINDOW": move_window,
    "RESIZE_WINDOW": resize_window,
    "FOCUS_WINDOW": focus_window,
    "SWITCH_WINDOW": switch_window,
    "CLOSE_WINDOW": close_window,
    "SNAP_WINDOW": snap_window,
    "SHOW_DESKTOP": show_desktop,
    "LOCK_SCREEN": lock_screen,
    # SYSTEM
    "EXIT": exit_iris,
    "SHUTDOWN": shutdown,
    "RESTART": restart,
    "SLEEP": sleep,
    "HIBERNATE": hibernate,
    "LOCK_PC": lock_pc,
    "LOG_OUT": log_out,
    "CANCEL_SHUTDOWN": cancel_shutdown,
    "SYSTEM_INFO": system_info,
    "CPU_USAGE": cpu_usage,
    "GPU_USAGE": gpu_usage,
    "RAM_USAGE": ram_usage,
    "DISK_USAGE": disk_usage,
    "BATTERY_STATUS": battery_status,
    "NETWORK_STATUS": network_status,
    "OS_INFO": os_info,
    # AUDIO & MEDIA
    "PLAY_MUSIC": play_music,
    "PAUSE_MEDIA": pause_media,
    "RESUME_MEDIA": resume_media,
    "STOP_MEDIA": stop_media,
    "NEXT_TRACK": next_track,
    "PREVIOUS_TRACK": previous_track,
    "VOLUME_UP": volume_up,
    "VOLUME_DOWN": volume_down,
    "SET_VOLUME": set_volume,
    "MUTE": mute,
    "UNMUTE": unmute,
    "PLAY_VIDEO": play_video,
    "STOP_VIDEO": stop_video,
    # SCREEN & INPUT
    "SCREENSHOT": screenshot,
    "SCREENSHOT_FULL": screenshot_full,
    "SCREENSHOT_WINDOW": screenshot_window,
    "SCREENSHOT_REGION": screenshot_region,
    "SCREEN_RECORD": screen_record,
    "STOP_SCREEN_RECORD": stop_screen_record,
    "TYPE_TEXT": type_text,
    "PRESS_KEY": press_key,
    "PRESS_KEYS": press_keys,
    "MOUSE_CLICK": mouse_click,
    "MOUSE_MOVE": mouse_move,
    "SCROLL": scroll,
    "DRAG": drag,
    # PRODUCTIVITY
    "CREATE_NOTE": create_note,
    "READ_NOTE": read_note,
    "EDIT_NOTE": edit_note,
    "DELETE_NOTE": delete_note,
    "OPEN_DOCUMENT": open_document,
    "CREATE_DOCUMENT": create_document,
    "OPEN_CALENDAR": open_calendar,
    "CREATE_REMINDER": create_reminder,
    "SET_TIMER": set_timer,
    "CANCEL_TIMER": cancel_timer,
    # CLIPBOARD
    "COPY": copy,
    "PASTE": paste,
    "READ_CLIPBOARD": read_clipboard,
    "WRITE_CLIPBOARD": write_clipboard,
    "CLEAR_CLIPBOARD": clear_clipboard,
    "CLIPBOARD_HISTORY": clipboard_history,
    # SEARCH & INFORMATION
    "WEB_SEARCH": web_search,
    "SEARCH_PC": search_pc,
    "SEARCH_FILES": search_files,
    "CALCULATE": calculate,
    "GET_DATE": get_date,
    "GET_TIME": get_time,
    "WEATHER": weather,
    "NEWS": news,
    # NETWORK
    "WIFI_ON": wifi_on,
    "WIFI_OFF": wifi_off,
    "WIFI_STATUS": wifi_status,
    "CONNECT_WIFI": connect_wifi,
    "DISCONNECT_WIFI": disconnect_wifi,
    "BLUETOOTH_ON": bluetooth_on,
    "BLUETOOTH_OFF": bluetooth_off,
    "BLUETOOTH_STATUS": bluetooth_status,
    "NETWORK_INFO": network_info,
    "PING_HOST": ping_host,
    # HARDWARE
    "BATTERY_HEALTH": battery_health,
    "CPU_STATUS": cpu_status,
    "GPU_STATUS": gpu_status,
    "RAM_STATUS": ram_status,
    "DISK_STATUS": disk_status,
    "TEMPERATURE_STATUS": temperature_status,
    "DISPLAY_INFO": display_info,
    "AUDIO_DEVICE_INFO": audio_device_info,
    "MICROPHONE_STATUS": microphone_status,
    # SECURITY
    "CHANGE_PASSWORD": change_password,
    "ENABLE_FIREWALL": enable_firewall,
    "DISABLE_FIREWALL": disable_firewall,
    "CHECK_SECURITY_STATUS": check_security_status,
    "CHECK_RUNNING_PROCESSES": check_running_processes,
    # PROCESSES
    "LIST_PROCESSES": list_processes,
    "FIND_PROCESS": find_process,
    "PROCESS_INFO": process_info,
    "START_PROCESS": start_process,
    "STOP_PROCESS": stop_process,
    "KILL_PROCESS": kill_process,
    "CHECK_PROCESS_STATUS": check_process_status,
    # SOFTWARE
    "INSTALL_SOFTWARE": install_software,
    "UNINSTALL_SOFTWARE": uninstall_software,
    "UPDATE_SOFTWARE": update_software,
    "CHECK_UPDATES": check_updates,
    "LIST_INSTALLED_SOFTWARE": list_installed_software,
    "LAUNCH_SOFTWARE": launch_software,
    # IRIS
    "WAKE_WORD": wake_word,
    "ENABLE_WAKE_WORD": enable_wake_word,
    "DISABLE_WAKE_WORD": disable_wake_word,
    "CHANGE_WAKE_WORD": change_wake_word,
    "VOICE_MODE": voice_mode,
    "TEXT_MODE": text_mode,
    "SLEEP_MODE": sleep_mode,
    "WAKE_IRIS": wake_iris,
    "STOP_IRIS": stop_iris,
    "RESTART_IRIS": restart_iris,
    "IRIS_STATUS": iris_status,
    # AI
    "AI_FALLBACK": ai_fallback,
    "ASK_AI": ask_ai,
    "SUMMARIZE": summarize,
    "EXPLAIN": explain,
    "TRANSLATE": translate,
    "REWRITE": rewrite,
    "GENERATE_TEXT": generate_text,
    "ANALYZE_TEXT": analyze_text,
    "ANALYZE_FILE": analyze_file,
    # AUTOMATION
    "EXECUTE_TASK": execute_task,
    "RUN_SEQUENCE": run_sequence,
    "CREATE_AUTOMATION": create_automation,
    "RUN_AUTOMATION": run_automation,
    "STOP_AUTOMATION": stop_automation,
    "LIST_AUTOMATIONS": list_automations,
}
